### PR TITLE
Release1.0

### PR DESCRIPTION
**Pull request by nicolas-f**
- About #195 add a setting to get user noise knowledge profile
- Show menu in settings activity

### CODE REVIEW

**Comment by ebocher** [comment]
Are you sure to release right now ?
The last features have not be tested no ?

**Comment by Picaut** [comment]
There are few minor correction before release 1.0.

**Comment by nicolas-f** [comment]
In Android there is a Production and Beta version. Production version must be an old beta version. So there will be a beta 1.0, and the same apk will be used to the Production publication.

**Comment by ebocher** [comment]
What about if some fixes are needed on the 1.0 beta ?

**Comment by nicolas-f** [comment]
Then a new beta will be added.

**Comment by nicolas-f** [comment]
All new apk will first be published as beta version. As we target a production version for this week or next week we cannot add new features, so the production version will be 1.0.X

**Pull request merged**
