### PR TITLE
Release1.0.4

### PR DESCRIPTION
**Pull request by nicolas-f**
- Force portrait mode in description activity about #216
- Upgrade version
- Add two new languages, German and Chinese
- Handle number format exception, about #244
- Handle NPE, about #245

### CODE REVIEW

**Comment by ebocher** [comment]
Please wait a validation for the Chinese language.

**Comment by nicolas-f** [comment]
Ok to publish ?

**Comment by Picaut** [comment]
Yes

**Comment by ebocher** [comment]
+100

**Pull request merged**
